import { getTaskIds, loadWaves } from "./waves.js";
import { loadWaveSize } from "./settings.js";

function buildPlanSlicePatcher(waveSize) {
  return function patchPlanSlice(args) {
    const { mid, state } = args;
    const sid = state.activeSlice.id;
    args.prompt += `

## 🛑 CRITICAL: AGGRESSIVE FINE-GRAINED PARALLELISM (WAVES.json)

This slice uses **Strict Wave-Based Parallel Execution**. Your goal is to maximize concurrency. Tasks in the same wave run SIMULTANEOUSLY in fully isolated subagent sandboxes. Tasks in different waves run sequentially.

### 🧠 How to Design for Maximum Concurrency

LLMs naturally tend to create sequential chains (e.g., Task 1 -> Task 2 -> Task 3). **YOU MUST BREAK THIS HABIT.** 

1. **The Strict Dependency Rule:** Task B should ONLY be placed in Wave N+1 if it literally cannot be written without reading the code/files generated by Task A in Wave N. 
2. **Orthogonal Splitting:** If tasks touch different files, different components, or different API endpoints, they belong in the **SAME WAVE**.
3. **Micro-Tasks:** Decompose monolithic tasks. "Build Dashboard" is bad. "Build Dashboard Header", "Build Dashboard Sidebar", "Build Dashboard Chart Component" all running in Wave 1 is **EXCELLENT**.
4. **Max Capacity:** You can run up to **${waveSize}** tasks concurrently per wave. Try to fill this capacity! If you have 8 independent components to build, put all 8 in Wave 1.

### 📝 WAVES.json Definition

You must create \`.gsd/milestones/${mid}/slices/${sid}/WAVES.json\`. 
Map each Task ID to a positive-integer wave number (1 = first wave, 2 = second, etc.).

\`\`\`json
{
  "T01": 1,
  "T02": 1,
  "T03": 1,
  "T04": 2
}
\`\`\`
*(In this example, T01, T02, and T03 run at the exact same time. T04 waits for them to finish.)*

**Constraint:** Max **${waveSize}** tasks per wave. If you have ${waveSize + 1} tasks that could be parallel, put the first ${waveSize} in Wave N, and the remaining 1 in Wave N+1.`;
    return args;
  };
}

function buildEnforceWaveRule(waveSize, capturedCtx, reactiveGraph) {
  return {
    name: "executing → enforce-explicit-waves",
    match: async ({ state, mid, basePath }) => {
      if (state.phase !== "executing" || !state.activeSlice) return null;
      const sid = state.activeSlice.id;
      const allTaskIds = getTaskIds(basePath, mid, sid);
      const wavePlan = loadWaves(basePath, mid, sid, allTaskIds);
      if (wavePlan.ok) return null;

      capturedCtx?.ui?.notify(`WAVES.json: ${wavePlan.reason}`, "warning");

      if (reactiveGraph?.clearReactiveState)
        reactiveGraph.clearReactiveState(basePath, mid, sid);

      return {
        action: "dispatch",
        unitType: "plan-slice",
        unitId: `${mid}/${sid}`,
        prompt: `# 🚨 RESTRUCTURE REQUIRED: Broken WAVES.json Plan

**Root Error:** ${wavePlan.reason}

Your previous task plan failed either validation or concurrency checks. You must COMPLETELY REDESIGN the task breakdown and WAVES.json.

### Restructuring Directives:
- **Fix the Error:** Ensure every single task ID is mapped to a valid wave integer in WAVES.json.
- **Eliminate Fake Dependencies:** If your previous plan had 5 waves with 1 task each, you failed at parallelism. Smash independent tasks together into the SAME WAVE.
- **Granularity:** If a task is too big to be done in parallel with others, SPLIT IT into smaller parallel tasks.
- **Max Wave Size:** Remember the hard limit is **${waveSize}** tasks per wave. 

Output a highly-parallel, strictly orthogonal task plan and call \`gsd_plan_slice\`.`
      };
    }
  };
}

function buildWaveReactiveRule(waveSize, capturedCtx, dbModule, promptsModule, reactiveGraph, prefsModels) {
  return {
    name: "executing → explicit-reactive-execute (true parallel dispatch)",
    match: async ({ state, mid, midTitle, basePath, prefs, sessionContextWindow, modelRegistry }) => {
      if (state.phase !== "executing" || !state.activeTask || !state.activeSlice) return null;
      if (!prefs?.reactive_execution?.enabled) return null;

      const sid = state.activeSlice.id;
      const sTitle = state.activeSlice.title;
      const subagentModel = prefs?.reactive_execution?.subagent_model
        ?? prefsModels?.resolveModelWithFallbacksForUnit?.("subagent")?.primary;

      const allTaskIds = getTaskIds(basePath, mid, sid);
      const wavePlan = loadWaves(basePath, mid, sid, allTaskIds);
      if (!wavePlan.ok) {
        if (reactiveGraph?.clearReactiveState) reactiveGraph.clearReactiveState(basePath, mid, sid);
        return null;
      }

      const dbAvailable = typeof dbModule?.isDbAvailable === "function" && dbModule.isDbAvailable();
      const completed = new Set();
      const running = [];
      const unstarted = [];

      // 1. Fine-grained state machine: distinguish completed / running / unstarted
      for (const tid of allTaskIds) {
        let status = "pending";
        if (dbAvailable && typeof dbModule?.getTask === "function") {
          const dbTask = dbModule.getTask(mid, sid, tid);
          if (dbTask && dbTask.status) status = dbTask.status.toLowerCase();
        }

        const waveNum = wavePlan.waves[tid];

        if (["complete", "done", "skipped", "success"].includes(status)) {
          completed.add(tid);
        } else if (["running", "in_progress", "active", "dispatched"].includes(status)) {
          running.push({ id: tid, wave: waveNum });
        } else {
          unstarted.push({ id: tid, wave: waveNum });
        }
      }

      if (unstarted.length === 0) {
        if (running.length === 0 && reactiveGraph?.clearReactiveState) {
          reactiveGraph.clearReactiveState(basePath, mid, sid);
        }
        return null; // all done, or all still running — nothing new to dispatch
      }

      // 2. Strict wave barrier: find the minimum wave among incomplete tasks
      const incompleteTasks = [...running, ...unstarted];
      incompleteTasks.sort((a, b) => a.wave - b.wave);
      const activeWave = incompleteTasks[0].wave;

      // Only dispatch tasks belonging to the current active wave
      const eligibleToStart = unstarted.filter(t => t.wave === activeWave).map(t => t.id);

      if (eligibleToStart.length === 0) {
        return null; // current wave has running tasks but none unstarted — wait
      }

      // 3. Concurrency throttle: respect waveSize cap
      const runningInActiveWave = running.filter(t => t.wave === activeWave).length;
      if (runningInActiveWave >= waveSize) {
        return null; // concurrency limit reached for this wave — wait
      }

      // Deterministic ordering
      const TASK_COLLATOR = new Intl.Collator("en", { numeric: true, sensitivity: "base" });
      eligibleToStart.sort(TASK_COLLATOR.compare);

      // 4. FIX: dispatch exactly 1 task per tick. The engine state loop
      //    will continuously invoke this rule, spinning up N isolated subagents.
      const selectedTask = eligibleToStart[0];
      const selected = [selectedTask];

      // Compute context for the prompt
      const waveNumbers = [...new Set(allTaskIds.map(id => wavePlan.waves[id]))].sort((a, b) => a - b);
      const totalWaves = waveNumbers.length;
      const futureTasks = unstarted.filter(t => t.wave > activeWave).map(t => `${t.id} (W${t.wave})`);

      capturedCtx?.ui?.notify(
        `Spawning Agent for ${selectedTask} (Wave ${activeWave}/${totalWaves}) [Active: ${runningInActiveWave + 1}/${waveSize}]`,
        "info"
      );

      const unitId = `${mid}/${sid}/reactive+${selectedTask}`;

      if (reactiveGraph?.saveReactiveState) {
        reactiveGraph.saveReactiveState(basePath, mid, sid, {
          sliceId: sid,
          completed: Array.from(completed),
          dispatched: selected,
          currentWave: activeWave,
          graphSnapshot: { taskCount: allTaskIds.length, edgeCount: 0, readySetSize: eligibleToStart.length, ambiguous: false },
          updatedAt: new Date().toISOString()
        });
      }

      const basePrompt = await promptsModule.buildReactiveExecutePrompt(
        mid, midTitle, sid, sTitle, selected, basePath, subagentModel,
        { sessionContextWindow, modelRegistry }
      );

      const waveContextBlock = `

## 🌊 CONCURRENT WAVE EXECUTION CONTEXT 🌊

You are a highly-focused subagent. You have been assigned EXACTLY ONE TASK as part of **WAVE ${activeWave} of ${totalWaves}**. 
Other agents are concurrently working on other tasks in this wave.

- ✅ **Completed (Prior Waves):** ${Array.from(completed).join(", ") || "(none)"} (Their code is ready to use).
- 🚀 **YOUR ASSIGNED TASK:** **${selectedTask}**
- ⏳ **Upcoming (Future Waves):** ${futureTasks.join(", ") || "(none)"}

### 🛑 STRICT Directives:
1. **FOCUS ONLY ON ${selectedTask}:** Do not attempt to implement any logic belonging to upcoming tasks.
2. **DO NOT OVERWRITE OTHERS:** Be mindful that other agents are modifying files right now. Only modify exactly what is needed for ${selectedTask}.`;

      return {
        action: "dispatch",
        unitType: "reactive-execute",
        unitId,
        prompt: basePrompt + waveContextBlock
      };
    }
  };
}

export function patchDispatchRules(core, pi, capturedCtx) {
  const DISPATCH_RULES = core["auto-dispatch"].DISPATCH_RULES;
  if (!Array.isArray(DISPATCH_RULES)) {
    capturedCtx?.ui?.notify?.("DISPATCH_RULES is not an array — cannot patch", "error");
    return;
  }

  const waveSize = loadWaveSize(capturedCtx);
  const planSlicePatcher = buildPlanSlicePatcher(waveSize, capturedCtx);
  const reactiveGraph = core["reactive-graph"];
  const dbModule = core["gsd-db"];
  const promptsModule = core["auto-prompts"];
  const prefsModels = core["preferences-models"];

  const planRuleIdx = DISPATCH_RULES.findIndex(r => r.name === "planning → plan-slice");
  if (planRuleIdx !== -1) {
    const originalRule = DISPATCH_RULES[planRuleIdx];
    const originalMatch = originalRule.match;
    DISPATCH_RULES[planRuleIdx] = {
      ...originalRule,
      match: async (args) => {
        const result = await originalMatch(args);
        if (!result) return null;
        return planSlicePatcher(result);
      }
    };
  }

  const reactiveRuleIdx = DISPATCH_RULES.findIndex(r =>
    r.name.includes("reactive-execute (parallel dispatch)")
  );
  if (reactiveRuleIdx !== -1) {
    DISPATCH_RULES.splice(reactiveRuleIdx, 1,
      buildEnforceWaveRule(waveSize, capturedCtx, reactiveGraph),
      buildWaveReactiveRule(waveSize, capturedCtx, dbModule, promptsModule, reactiveGraph, prefsModels)
    );
  }
}
